name: Rust

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
          cargo build
          ls
          ls *
          cp ./target/*/matrix-commander-rs .
          ls -l ./matrix-commander-rs

    - uses: actions/upload-artifact@v4
      with:
        name: plain-linux
        path: |
            ./matrix-commander-rs
        retention-days: 1

    # https://github.com/softprops/action-gh-release
    - name: Release
      uses: "softprops/action-gh-release@v2"
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        generate_release_notes: true
        files: |
            ./matrix-commander-rs
