name: Rust-by-gh

# only works on tags, if there is no tag it will not work
# cannot start it manually

on:
  # fires when there is a git push with version tag
  push:
    # this would trigger twice, once for tag v, once for branch main
    # branches: [ "main" ]
    tags:
      - "v*"
  # pull_request:
  #   branches: [ "main" ]
  #   tags:
  #     - "v*"
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name for release'
        required: false
        default: nightly
        
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      # Don't build if we dont have a version tag tag, cannot create release without a version tag anyways
      # if: startsWith(github.ref, 'refs/tags/')
    
    - name: Build
      run: |
          rustc -vV
          cargo build --release
          ls -l target target/*
          mv ./target/*/matrix-commander-rs matrix-commander-rs.linux-$(uname -m)
          ls -l ./matrix-commander-rs*
          cargo clean
          # now cross compile
          sudo apt-get install podman
          cargo install cross
          cross run --target aarch64-unknown-linux-gnu
          ls -l target target/*
          mv ./target/*/matrix-commander-rs matrix-commander-rs.aarch64-unknown-linux-gnu
          ls -l ./matrix-commander-rs*
          cargo clean
          

    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: plain-linux
    #     path: |
    #         ./matrix-commander-rs*
    #     retention-days: 1

    # https://github.com/softprops/action-gh-release
    - name: Release
      uses: "softprops/action-gh-release@v2"
      if: startsWith(github.ref, 'refs/tags/')
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        generate_release_notes: true
        files: |
            ./matrix-commander-rs*
